# --- Jihed's Bash Configuration ---

# 1. Colors & Prompt 
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '


# 2. Source aliases if they exist
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# 3. History settings
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s histappend

# 4. Enable color support
if [ -x /usr/bin/dircolors ]; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi
